[workspace]
members = ["host/moos-gateway"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.97.1"
license = "GPL-3.0-only"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"

[profile.release]
codegen-units = 1
lto = "thin"
overflow-checks = true
panic = "abort"
strip = "symbols"
